2024-12-14 00:14:01,954 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\pythonProject\My_work\module_12\module_12_4\tests_12_4.py", line 32, in test_run
    runner = Runner(("Василий",), 10)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject\My_work\module_12\module_12_4\rt_with_exeptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано tuple
2024-12-14 00:14:01,956 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\pythonProject\My_work\module_12\module_12_4\tests_12_4.py", line 20, in test_walk
    runner = Runner("Степан", -10)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject\My_work\module_12\module_12_4\rt_with_exeptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
